/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package collections;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NAM PC
 */
public class QuanLySinhVien extends javax.swing.JFrame {
    List<Student> list = new ArrayList<>();
    /**
     * Creates new form QuanLySinhVien
     */
    public QuanLySinhVien() {
        initComponents();
        setLocationRelativeTo(null);
    }
    public void addStudent(){
        Student sv = new Student();
        sv.name = txtname.getText();
        sv.marks = Double.parseDouble(txtdiem.getText());
        sv.major = (String) cbonganh.getSelectedItem();
        
        list.add(sv);
        // hiển thị học lực và phần thưởng
        txthocluc.setText(sv.getGrade());
        chkcophanthuong.setSelected(sv.isBonus());
    }
    public void removeStudent(){
        int index = btlbangquanlysinhvien.getSelectedRow();
        list.remove(index);
    }
    public void updateStudent(){
        // lấy sv tại vị trí được chọn trên bảng
        int index = btlbangquanlysinhvien.getSelectedRow();
        Student sv = list.get(index);
        
        // cập nhận thông tin mới 
        sv.name = txtname.getText();
        sv.marks = Double.parseDouble(txtdiem.getText());
        sv.major = (String) cbonganh.getSelectedItem();
        txthocluc.setText(sv.getGrade());
        chkcophanthuong.setSelected(sv.isBonus());
    }
    public void fillToTable(){
        DefaultTableModel model = (DefaultTableModel) btlbangquanlysinhvien.getModel();
        model.setRowCount(0);
        
        for (Student sv : list) {
            Object row[] = new Object []{sv.name,sv.marks,sv.major,sv.getGrade(),sv.isBonus()};
            model.addRow(row);
        }
    }
    public void showDetail(){
        // lấy sv tại vị trí được chọn trên bảng
        int index = btlbangquanlysinhvien.getSelectedRow();
        Student sv = list.get(index);
        
        // cập nhận thông tin mới 
        sv.name = txtname.getText();
        sv.marks = Double.parseDouble(txtdiem.getText());
        sv.major = (String) cbonganh.getSelectedItem();
        txthocluc.setText(sv.getGrade());
        chkcophanthuong.setSelected(sv.isBonus());
    }
    public void orderByName(){
        Comparator<Student> com = new Comparator<Student>() {
            @Override
            public int compare(Student o1, Student o2) {
                return o1.name.compareTo(o2.name);
            }
        };
        Collections.sort(list,com);
    }
    public void orderByMarks(){
        Comparator<Student> com = new Comparator<Student>() {
            @Override
            public int compare(Student o1, Student o2) {
                Double d1 = o1.marks;
                Double d2 = o2.marks;
                return d1.compareTo(d2);
            }
        };
        Collections.sort(list,com);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblquanlysinhvien = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        lbldiem = new javax.swing.JLabel();
        lblhocluc = new javax.swing.JLabel();
        lblnganh = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtdiem = new javax.swing.JTextField();
        cbonganh = new javax.swing.JComboBox<>();
        txthocluc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        btlbangquanlysinhvien = new javax.swing.JTable();
        chkcophanthuong = new javax.swing.JCheckBox();
        btnthem = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btncapnhat = new javax.swing.JButton();
        btnnhapmoi = new javax.swing.JButton();
        btnsapxeptheoten = new javax.swing.JButton();
        sapxeptheodiem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblquanlysinhvien.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblquanlysinhvien.setForeground(new java.awt.Color(255, 0, 0));
        lblquanlysinhvien.setText("QUẢN LÝ SINH VIÊN");

        lblname.setText("HỌ VÀ TÊN");

        lbldiem.setText("ĐIỂM");

        lblhocluc.setText("HỌC LỰC");

        lblnganh.setText("NGÀNH");

        cbonganh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ứng dụng phần mềm", "thiết kế web" }));

        txthocluc.setEnabled(false);

        btlbangquanlysinhvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "HỌ VÀ TÊN", "ĐIỂM", "NGÀNH", "HỌC LỰC", "THƯỞNG"
            }
        ));
        btlbangquanlysinhvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btlbangquanlysinhvienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(btlbangquanlysinhvien);

        chkcophanthuong.setText("Có phần thưởng ?");

        btnthem.setText("Thêm ");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btncapnhat.setText("Cập nhật");
        btncapnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncapnhatActionPerformed(evt);
            }
        });

        btnnhapmoi.setText("Nhập mới");
        btnnhapmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnhapmoiActionPerformed(evt);
            }
        });

        btnsapxeptheoten.setText("Sắp xếp theo tên");
        btnsapxeptheoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsapxeptheotenActionPerformed(evt);
            }
        });

        sapxeptheodiem.setText("Sắp xếp theo điểm");
        sapxeptheodiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sapxeptheodiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(278, Short.MAX_VALUE)
                .addComponent(lblquanlysinhvien)
                .addGap(200, 200, 200))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnsapxeptheoten, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sapxeptheodiem, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblhocluc)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblname)
                            .addGap(18, 18, 18)
                            .addComponent(txtname))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbldiem)
                                .addComponent(lblnganh))
                            .addGap(35, 35, 35)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtdiem)
                                .addComponent(txthocluc)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(chkcophanthuong)
                                        .addComponent(cbonganh, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnthem)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnxoa)
                                            .addGap(18, 18, 18)
                                            .addComponent(btncapnhat)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnnhapmoi)))
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblquanlysinhvien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblname)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldiem)
                    .addComponent(txtdiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnganh)
                    .addComponent(cbonganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblhocluc)
                    .addComponent(txthocluc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(chkcophanthuong)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthem)
                    .addComponent(btnxoa)
                    .addComponent(btncapnhat)
                    .addComponent(btnnhapmoi))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsapxeptheoten)
                    .addComponent(sapxeptheodiem))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnnhapmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnhapmoiActionPerformed
        // TODO add your handling code here:
        txtname.setText("");
        txtdiem.setText("");
        txthocluc.setText("");
        chkcophanthuong.setSelected(false);
        
    }//GEN-LAST:event_btnnhapmoiActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        this.addStudent();
        this.fillToTable();
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        this.removeStudent();
        this.fillToTable();
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btncapnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncapnhatActionPerformed
        // TODO add your handling code here:
        this.updateStudent();
        this.fillToTable();
    }//GEN-LAST:event_btncapnhatActionPerformed

    private void btlbangquanlysinhvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btlbangquanlysinhvienMouseClicked
        // TODO add your handling code here:
        this.showDetail();
    }//GEN-LAST:event_btlbangquanlysinhvienMouseClicked

    private void btnsapxeptheotenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsapxeptheotenActionPerformed
        // TODO add your handling code here:
        this.orderByName();
        this.fillToTable();
    }//GEN-LAST:event_btnsapxeptheotenActionPerformed

    private void sapxeptheodiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sapxeptheodiemActionPerformed
        // TODO add your handling code here:
        this.orderByMarks();
        this.fillToTable();
    }//GEN-LAST:event_sapxeptheodiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLySinhVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable btlbangquanlysinhvien;
    private javax.swing.JButton btncapnhat;
    private javax.swing.JButton btnnhapmoi;
    private javax.swing.JButton btnsapxeptheoten;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnxoa;
    private javax.swing.JComboBox<String> cbonganh;
    private javax.swing.JCheckBox chkcophanthuong;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbldiem;
    private javax.swing.JLabel lblhocluc;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblnganh;
    private javax.swing.JLabel lblquanlysinhvien;
    private javax.swing.JButton sapxeptheodiem;
    private javax.swing.JTextField txtdiem;
    private javax.swing.JTextField txthocluc;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
