CREATE DATABASE QLNS
GO
USE QLNS
GO

CREATE TABLE PhongBan(
MaPB NVARCHAR(10) PRIMARY KEY,
TenPB NVARCHAr(50) NOT NULL,
MaTruongPhong NVARCHAR(10)
);

GO

CREATE TABLE NhanVien(
MaNV NVARCHAR(10) PRIMARY KEY,
HoNV NVARCHAr(50) NOT NULL,
TenNV NVARCHAr(50) NOT NULL,
NamSinh DATE,
DiaChi NVARCHAR(12),
GioiTinh BIT,
Luong float,
MaPB NVARCHAR(10),
CONSTRAINT FK_NV_PB FOREIGN KEY (MaPB) REFERENCES PhongBan(MaPB)
);
GO

CREATE TABLE DuAn(
MaDA INT IDENTITY(1,1) PRIMARY KEY,
TenDA NVARCHAR(250),
NgayBD DATE,
NgayKT DATE
);

GO

CREATE TABLE QuanLyDuAn(
MaDA INT,
MaNV NVARCHAR(10),
NgayThamGia DATE,
NgayKetThuc DATE,
SoGio INT,
VaiTro NVARCHAR(50),
PRIMARY KEY (MaDA, MaNV),
CONSTRAINT FK_DA_QLDA FOREIGN KEY (MaDA) REFERENCES DuAn(MaDA),
CONSTRAINT FK_NV_QLDA FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)
)
GO
-- add column
ALTER TABLE NhanVien
ADD Email NVARCHAR(100);

-- delete column
ALTER TABLE NhanVien
DROP COLUMN Email

-- rang buoc
ALTER TABLE NhanVien
ADD CONSTRAINT checkLuong
CHECK(Luong >=0);
------------------------------------------
CREATE TABLE PhongBan2(
MaPB NVARCHAR(10) NOT NULL,
TenPB NVARCHAr(50) NOT NULL,
MaTruongPhong NVARCHAR(10)
);
GO
ALTER TABLE PhongBan2
ADD CONSTRAINT PK_ID PRIMARY KEY (MaPB)  
GO 

-- add column
ALTER TABLE PhongBan2
ADD MoTa NVARCHAR(255);

-- 

ALTER TABLE QuanLyDuAn
ADD CONSTRAINT checkSoGio
CHECK(SoGio >=0);

ALTER TABLE PhongBan2
DROP CONSTRAINT PK_ID;
-------------------------------
CREATE TABLE NhanVien2(
MaNV NVARCHAR(10) PRIMARY KEY,
HoNV NVARCHAr(50) NOT NULL,
TenNV NVARCHAr(50) NOT NULL,
NamSinh DATE,
DiaChi NVARCHAR(12),
GioiTinh BIT,
Luong float,
MaPB NVARCHAR(10)
);
GO

ALTER TABLE NhanVien2
ADD CONSTRAINT FK_NV2_PB2 FOREIGN KEY (MaPB) REFERENCES PhongBan2(MaPB)

