/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PHAN1;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author NAM PC
 */
public class QuanLyNV extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyNV
     */
    public QuanLyNV() {
        initComponents();
        setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblqlnv = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        lblluong = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtdate = new javax.swing.JTextField();
        txtluong = new javax.swing.JTextField();
        btnkiemtra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Nhân Viên");

        lblqlnv.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblqlnv.setForeground(new java.awt.Color(255, 0, 0));
        lblqlnv.setText("Quản Lý Nhân Viên");

        lblname.setText("HỌ VÀ TÊN");

        lbldate.setText("NGÀY SINH");

        lblluong.setText("LƯƠNG");

        btnkiemtra.setText("Kiểm tra");
        btnkiemtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkiemtraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblname)
                    .addComponent(lbldate)
                    .addComponent(lblluong))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnkiemtra)
                    .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtluong, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblqlnv))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblqlnv)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblname)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldate)
                    .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblluong)
                    .addComponent(txtluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnkiemtra)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnkiemtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkiemtraActionPerformed
        // TODO add your handling code here:
        /*không bỏ trống và tô vàng */
        String fullname = txtname.getText();
        String datetime = txtdate.getText();
        String luong = txtluong.getText();
        
        if (fullname.equals("")) {
            JOptionPane.showMessageDialog(this, "khong duoc bo trong ho va ten");
            txtname.setBackground(Color.YELLOW);
        }
        if (datetime.equals("")) {
            JOptionPane.showMessageDialog(this, "khong duoc bo trong ngay sinh");
            txtdate.setBackground(Color.YELLOW);
        }
        if (luong.equals("")) {
            JOptionPane.showMessageDialog(this, "khong duoc bo trong luong");
            txtluong.setBackground(Color.YELLOW);
        }
        if (fullname.length()>0) {
            txtname.setBackground(Color.WHITE);
        }
        
       /*luong la so duong*/
        try {
            double so = Double.parseDouble(luong);
            if (so > 0) {
                JOptionPane.showMessageDialog(this, "so luong hop le");
                txtluong.setBackground(Color.WHITE);
            } else {
                JOptionPane.showMessageDialog(this, "so luong khong hop le");
                txtluong.setBackground(Color.YELLOW);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "hay nhap luong lon hon 0");
            txtluong.setBackground(Color.YELLOW);
        }
         /*ngay sinh dung dinh dang dd-MM-yyyy*/
        SimpleDateFormat formater = new SimpleDateFormat();
        
        try {
//            formater.applyPattern("dd-MM-yyyy");
//            Date date = formater.parse(datetime);
//            
//            formater.applyPattern("EEEE, dd-MM,yyyy");
//            String text2 = formater.format(date);
//            JOptionPane.showMessageDialog(this, text2);
            Date birthday = XDate.parse(datetime,"dd-MM-yyyy");
            txtdate.setBackground(Color.WHITE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ngay sinh không đúng định dạng");
            txtdate.setBackground(Color.YELLOW);
        }
    }//GEN-LAST:event_btnkiemtraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyNV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnkiemtra;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lblluong;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblqlnv;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtluong;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
